apiVersion: v1
kind: Template
labels:
  app: ola
metadata:
  annotations:
    description: ola production route
    iconClass: icon-java
    tags: blue-green
  name: production-route
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${APPLICATION_NAME}-${APPLICATION_INSTANCE}
      weight: 100
parameters:
- displayName: Application instance
  name: APPLICATION_INSTANCE
  value: blue
- displayName: Application name
  name: APPLICATION_NAME
  required: true
