# Pipeline
  kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: cicd-pipeline
      name: cicd-pipeline
    name: cicd-pipeline
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
  spec:
    triggers:
      - type: GitHub
        github:
          secret: abc
      - type: Generic
        generic:
          secret: abc
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: 'http://github.com/jbrannst/ola.git'
        ref: master
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    output: {}
    resources: {}
    postCommit: {}
    nodeSelector: {}
  status:
    lastVersion: 1
